name: Checkov

on:
  workflow_call:
    inputs:
      skip_check_file:
        required: false
        default: ".checkov"
        type: string

permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write
  pull-requests: write

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov-action

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Retrieve skip check
        id: skip_check
        uses: mikefarah/yq@v4.30.8
        env:
          INPUT_SKIP_CHECK_FILE: ${{ inputs.skip_check_file }}
        with:
          cmd: |
            if [[ ! -f "${INPUT_SKIP_CHECK_FILE}" ]]; then
              echo "skip_check: []" > ${INPUT_SKIP_CHECK_FILE}
            fi
            yq '.skip_check | join (",")' ${INPUT_SKIP_CHECK_FILE}

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./
          output_format: sarif
          output_file_path: results.sarif
          quiet: true
          soft_fail: true
          skip_check: ${{ steps.skip_check.outputs.result }}

      - name: Annotation the PR
        if: github.event_name == 'pull_request'
        uses: sett-and-hive/sarif-to-comment-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
          sarif-file: results.sarif
          title: "Security scanning results"
          odc-sarif: false

      - name: Upload SARIF file
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
