name: pre-commit-basic

on:
  workflow_call:
    inputs:
      tofu_version:
        required: false
        type: string
        default: '1.7.3'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ github.event.inputs.tofu_version }}
        
    - uses: pre-commit/action@v3.0.1
      env:
        SKIP: no-commit-to-branch
