name: pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install tflint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      env:
        TFLINT_VERSION: v0.44.1

    - name: Use compact mode for tflint
      run: sed -i 's/"default"/"compact"/g' .tflint.hcl

    - uses: pre-commit/action@v3.0.0
      env:
        SKIP: no-commit-to-branch
        GITHUB_TOKEN: ${{ github.token }}
