name: pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install tflint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      env:
        TFLINT_VERSION: v0.48.0

    - name: Use compact mode for tflint
      run: sed -i 's/"default"/"compact"/g' .tflint.hcl

    - name: Install tfsort
      run: |
        get_machine_arch () {
          machine_arch=""
          case $(uname -m) in
              x86_64)   machine_arch="amd64" ;;
              arm64)    machine_arch="arm64" ;;
              aarch64)  dpkg --print-architecture | grep -q "arm64" && machine_arch="arm64" || machine_arch="arm" ;;
          esac
          echo $machine_arch
        }
        arch=$(get_machine_arch)
        download_url="https://github.com/AlexNabokikh/tfsort/releases/download/v${TFSORT_VERSION}/tfsort_${TFSORT_VERSION}_linux_${arch}.tar.gz"
        echo "Downloading ${download_url}"
        curl -s -L ${download_url} | tar xvz -C /usr/local/bin tfsort
        chmod +x /usr/local/bin
      env:
        TFSORT_VERSION: 0.2.3

    - uses: pre-commit/action@v3.0.0
      env:
        SKIP: no-commit-to-branch
        GITHUB_TOKEN: ${{ github.token }}
