name: Run Terraform init with update and provider lock on renovate PRs

on:
  workflow_call:
    secrets:
      PAT:
        description: Personal access token for cloning and committing
        required: true

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.PAT }}

    - name: Get Terraform version
      run: |
        echo "TERRAFORM_VERSION=$(grep -oP '(?<=terraform ).*' .tool-versions)" >> $GITHUB_ENV

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: "${{ env.TERRAFORM_VERSION }}"

    - name: Update atlantis version
      run: |
        sed -i 's/terraform_version: v.*/terraform_version: v'${{ env.TERRAFORM_VERSION }}'/g' atlantis.yaml
        git config --global url."https://github".insteadOf ssh://git@github

    - name: Run Terraform init update
      continue-on-error: true
      run: |
        fix_terraform() {
          local state_path=$1
          cd "$state_path"

          # Clone is available on https only
          find . -name "*.tf" -exec sed -i 's|source = "git@github.com:${{ github.repository }}/"|source = "git::https://github.com/${{ github.repository }}.git/"|g' {} \;

          terraform init -upgrade -backend=false -lock=false -input=false
          rm -rf .terraform # cleanup to save disk space
        }
        dir=$(pwd)
        for line in $(grep -oP '(?<=dir: ).*' atlantis.yaml); do
            fix_terraform "${dir}/${line}"
        done

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "renovate: Update Terraform lock file"
        file_pattern: "*"
        disable_globbing: true

    - if: ${{ github.event.pull_request.draft == true }}
      run: gh pr ready ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
