name: tfsec

on:
  workflow_call:
    inputs:
      config_file:
        required: false
        type: string

permissions:
  actions: read
  contents: read
  security-events: write
  statuses: write
  pull-requests: write

jobs:
  tfsec:
    name: tfsec scan
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: tfsec pr-commenter
        if: github.event_name == 'pull_request'
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          soft_fail_commenter: true
          working_directory: ""
          tfsec_args: --minimum-severity HIGH --force-all-dirs
          github_token: ${{ github.token }}

      - name: tfsec
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true
          config_file: ${{ inputs.config_file }}

      - name: Upload SARIF file
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
